#!/bin/bash
## 
## Enduro X Configuration File
##
## @file setndrx
## 
## -----------------------------------------------------------------------------
## Enduro/X Middleware Platform for Distributed Transaction Processing
## Copyright (C) 2015, ATR Baltic, SIA. All Rights Reserved.
## This software is released under one of the following licenses:
## GPL or ATR Baltic's license for commercial use.
## -----------------------------------------------------------------------------
## GPL license:
## 
## This program is free software; you can redistribute it and/or modify it under
## the terms of the GNU General Public License as published by the Free Software
## Foundation; either version 2 of the License, or (at your option) any later
## version.
##
## This program is distributed in the hope that it will be useful, but WITHOUT ANY
## WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
## PARTICULAR PURPOSE. See the GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License along with
## this program; if not, write to the Free Software Foundation, Inc., 59 Temple
## Place, Suite 330, Boston, MA 02111-1307 USA
##
## -----------------------------------------------------------------------------
## A commercial use license is available from ATR Baltic, SIA
## contact@atrbaltic.com
## -----------------------------------------------------------------------------
##

export NDRX_NODEID=1
# If 1 - then yes, if 0 - then not clusterised.
export NDRX_CLUSTERISED=1
# Load balance, 0 = process all locally, 100 = process all on remote servers
export NDRX_LDBAL=0
export NDRX_TOUT=60
export NDRX_ULOG=/tmp
export NDRX_QPREFIX=/n00b
export NDRX_SVCMAX=20000
export NDRX_SRVMAX=10000
export NDRX_QPATH=/dev/mqueue
export NDRX_SHMPATH=/dev/shm
# Milli seconds to wait for command
export NDRX_CMDWAIT=1
export NDRX_DPID=/tmp/ndrxd.pid
# Random key to indentify the processes beloning to this session (i.e. used in ps ef)
export NDRX_RNDK="0myWI5nu"
# System V Semaphores...
export NDRX_IPCKEY=44000

# Posix queue config (attribs..)
# Max number of messages that can be put in one queue
export NDRX_MSGMAX=1000
# Daemon Q size...
export NDRX_DQMAX=100
# Max message size (in bytes)
export NDRX_MSGSIZEMAX=10000
# Max fields for hashing UBF
export NDRX_UBFMAXFLDS=16000

# load the config if have one from tests

if [ -f ~/ndrx_home ]; then
. ~/ndrx_home
fi

# Log & levels
export NDRX_DMNLOG=/tmp/ndrxd.log
export NDRX_DMNLEV=5

export NDRX_LOG=/tmp/ndrx.log
export NDRX_LEV=5

# Correct the path so that ndrx can find ndrxd
export PATH=$PATH:`pwd`/../bin

export NDRX_CONFIG=`pwd`/ndrxconfig.xml
export NDRX_DEBUG_CONF=`pwd`/debug.conf
# UBFTAB
export FLDTBLDIR=`pwd`/../src/ubftab
export FIELDTBLS=test.fd

