# Do recursive builds
all:
	$(MAKE) -C 01_basic_ubf_call
	$(MAKE) -C 02_basic_string_call
	$(MAKE) -C 03_basic_carray_call
	$(MAKE) -C 05_basic_json_call
	$(MAKE) -C 06_ubf_marshal
	$(MAKE) -C 07_basic_durable_queue
	$(MAKE) -C 08_logging
